const main_data = {
  animation: [
    "animation.html",
    "loading.html",
    "normal.html",
    "國際賽.html",
    "tranform-filter/index.html",
    "footer/footer.html",
    "wordEffect.html",
  ],
  background: ["background.html"],
  button: [
    "button.html",
    "button2.html",
    "button3.html",
    "remember.html",
    "remember2.0/index.html",
    "mousemove.html",
  ],
  canvas: ["drawball.html", "調色盤.html", "小畫家"],
  card: [
    "border-cards",
    "Glass-morphism",
    "img-card",
    "img-light-card/card.html",
  ],
  Carry_system: ["Carry_system.html"],
  clipPath: ["index.html"],
  chat: ["chat-vanilla.html", "chat-jquery.html", "chat-vue.html", "chat2-vue.html"],
  chart: ["chart-v1-css.html", "chart-v1-js.html", "chart-v2-css.html"],
  hover: ["hover.html", "figcaption_on_hover.html", "mousemove.html"],
  input: ["input.html"],
  navbar: [
    "menu-hover-part2",
    "menu-hover",
    "navbar-RWD",
    "navbar-基本款",
    "自動縮放navbar/index.html",
    "自動縮放navbar/index2.html",
  ],
  new: [
    "accordion.html",
    "box.html",
    "cubic-bezier.html",
    "rounded-border-gradient.html",
    "scroll-driven-animations.html",
  ],
  parallax: ["scroll.html", "mousemove.html"],
  QandA: ["Q&A.html"],
  scroll: [
    "index.html",
    "opacity.html",
    "range.html",
    "scroll-anime/scroll-anime.html",
    "scroll-snap/scroll-snap.html",
  ],
  TodoList: ["index.html", "index-modal.html", "超簡單版/todoList.html"],
  slider: [
    "slider.html",
    "火車過山洞.html",
    "slider-responsiveImg.html",
    "slider-fade.html",
    "only-css.html",
    "vue-lg.html",
  ],
  light_dark_theme: ["index.html"],
  shopcar: ["shopcar-vanilla.html", "shopcar-jquery.html", "shopcar-vue.html"],
  components: [
    "頁面/index.html",
    "書店/index.html",
    "contactUs聯絡我們/index.html",
    "login登入/login.html",
    "極簡主義/index.html",
    "training/1102/index.html",
    "html-tag/index.html",
    "終極密碼/index.html",
  ],
};

export { main_data };
